[project]
name = "tgram"
dynamic = ["version"]
description = "HTTP Bot API Client"


authors = [{ name = "Zaid", email = "2ei@zaid.pro" }]
dependencies = [
    "asyncio",
    "aiohttp",
    "aiofiles"
]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

keywords = ["telegram bot api client"]

[tool.hatch.version]
path = "tgram/__init__.py"

# Used to call hatch_build.py
[tool.hatch.build.hooks.custom]

[project.urls]
Homepage = "https://github.com/2ei/tgram"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build]
exclude = [".github", ".gitignore", "examples"]

[tool.hatch.build.targets.sdist]
include = [
    "tgram",
]
exclude = [
    ".github/",
    ".gitignore",
    "examples/"
]

[tool.hatch.build.targets.wheel]
ignore-vcs = true
packages = ["tgram"]