[project]
name = "tgram"
dynamic = ["version"]
description = "HTTP Bot API Client"


authors = [{ name = "Zaid", email = "2ei@zaid.pro" }]
dependencies = [
    "asyncio",
    "aiohttp",
    "aiofiles"
]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

keywords = ["telegram bot api client"]

[project.urls]
Homepage = "https://github.com/2ei/tgram"